### ISSUE TITLE
Use Equinix red in the top nav bar

### ISSUE THREAD

**Issue by displague** [equinix-labs/equinix-labs-workshop#10]
As seen in https://equinix-labs.github.io/terraform-on-equinix-workshop/, adopt the Equinix brand's red color for the top nav bar.

**Comment by ctreatma** [comment]
After some investigation, "Equinix red" is already configured in this repo and all workshops created from it, but it doesn't take effect on the live workshop pages for most repos.  We need to update our configuration to match the documentation for using custom colors: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

**Comment by ocobles** [comment]
I opened this issue last year. The logs for the last repositories where it was still red have already expired, but I could verify that it was after the mkdocs version update 9.1.8 https://github.com/equinix-labs/eks-anywhere-on-equinix-metal-workshop/issues/5
