### ISSUE TITLE
Template should recommend renaming "Part 1" .. "Part 3" to match section titles

### ISSUE THREAD

**Issue by displague** [equinix-labs/equinix-labs-workshop#12]
"Part 1" ... "Part 3" are not intended to be used literally.

https://github.com/equinix-labs/equinix-labs-workshop/blob/main/CONTRIBUTING.md should be revised to say as much. The templates could be improved with comments that say to change that text.

**Comment by ctreatma** [comment]
I think it would also be helpful to document this by not using "Part n" as the page titles; we already do this for the "Conclusion" page.  Perhaps something like

1. Setup
2. Accomplish Some Goal
3. Accomplish Another Goal
4. Conclusion
